# Copyright 2018 - 2022, Mathijs Saey, Vrije Universiteit Brussel

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

on: [push, pull_request]

jobs:
  compile:
    runs-on: ubuntu-latest
    name: Check compiler output
    strategy:
      matrix:
        otp: ['28.2']
        elixir: ['1.19.4']
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - name: Get Elixir dependencies
        run: mix deps.get
      - name: Ensure no warnings are present
        run: mix compile --warnings-as-errors

  typecheck:
    runs-on: ubuntu-latest
    name: Check type annotations with Dialyzer
    strategy:
      matrix:
        otp: ['28.2']
        elixir: ['1.19.4']
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - name: Get Elixir dependencies
        run: mix deps.get
      - name: Run dialyzer to check type annotations
        run: mix dialyzer --format github

  test:
    runs-on: ubuntu-latest
    name: Run tests
    strategy:
      matrix:
        otp: ['24.3.4', '25.3.2', '26.2.5', '27.3.4', '28.2']
        elixir: ['1.15.8', '1.16.3', '1.17.3', '1.18.4', '1.19.4']
        # Exclude unsupported OTP/Elixir combinations
        exclude:
          - elixir: '1.15.8'
            otp: '27.3.4'
          - elixir: '1.15.8'
            otp: '28.2'
          - elixir: '1.16.3'
            otp: '27.3.4'
          - elixir: '1.16.3'
            otp: '28.2'
          - elixir: '1.17.3'
            otp: '24.3.4'
          - elixir: '1.17.3'
            otp: '28.2'
          - elixir: '1.18.4'
            otp: '24.3.4'
          - elixir: '1.18.4'
            otp: '28.2'
          - elixir: '1.19.4'
            otp: '24.3.4'
          - elixir: '1.19.4'
            otp: '25.3.2'

    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - name: Get Elixir dependencies
        run: mix deps.get
      - name: Run Elixir tests
        run: mix test

  format:
    runs-on: ubuntu-latest
    name: Check Elixir formatting
    strategy:
      matrix:
        otp: ['28.2']
        elixir: ['1.19.4']
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - name: Get Elixir dependencies
        run: mix deps.get
      - name: Check code formatting
        run: mix format --check-formatted

